const songQueue = [
  { title: "On My Way", singer: "Alan Walker", src: "music/1.m4a" ,image: "image/1.jpeg" },
  { title: "Side to side", singer: "Ariana Grande", src: "music/2.m4a" ,image: "image/2.jpeg"},
  { title: "Mayores", singer: "Becky G", src: "music/3.m4a" ,image: "image/3.jpeg"},
  { title: "Lovely", singer: "Billie Eilish", src: "music/4.m4a" ,image: "image/4.jpeg"},
  { title: "Havana", singer: "Camila Cabello", src: "music/5.m4a" ,image: "image/5.jpeg"},
  { title: "Gasolina", singer: "Daddy Yankee", src: "music/6.m4a" ,image: "image/6.jpeg"},
  { title: "Con Calma", singer: "Daddy Yankee", src: "music/7.m4a" ,image: "image/7.jpeg"},
  { title: "Sugar & Brownies", singer: "Dharia", src: "music/8.m4a" ,image: "image/8.jpeg"},
  { title: "Levitating", singer: "Dua Lipa", src: "music/9.m4a" ,image: "image/9.jpeg"},
  { title: "Shape of you", singer: "Ed Sheeran", src: "music/10.m4a",image: "image/10.jpeg" },
  { title: "Love me like you do", singer: "Ellie Goulding", src: "music/11.m4a" ,image: "image/11.jpeg" },
  { title: "Bailando", singer: "Enrique Iglesias", src: "music/12.m4a" ,image: "image/12.jpeg"},
  { title: "Subeme la Radio", singer: "Enrique Iglesias", src: "music/13.m4a" ,image: "image/13.jpeg"},
  { title: "Mi Gente", singer: "J Balvin", src: "music/14.m4a" ,image: "image/14.jpeg"},
  { title: "Baby", singer: "Justin Bieber", src: "music/15.m4a" ,image: "image/15.jpeg"},
  { title: "Industry Baby", singer: "Lil Nas X", src: "music/16.m4a" ,image: "image/16.jpeg"},
  { title: "Echame la Culpa", singer: "Luis Fonsi", src: "music/17.m4a" ,image: "image/17.jpeg"},
  { title: "Friends", singer: "Anne Marie", src: "music/18.m4a" ,image: "image/18.jpeg"},
  { title: "Calma", singer: "Pedro Capo", src: "music/19.m4a" ,image: "image/19.jpeg"},
  { title: "Gangnam Style", singer: "Psy", src: "music/20.m4a",image: "image/20.jpeg" },
  { title: "Safari", singer: "Serena", src: "music/21.m4a" ,image: "image/21.jpeg" },
  { title: "Chanta Je", singer: "Shakira", src: "music/22.m4a" ,image: "image/22.jpeg"},
  { title: "Hips Don't Lie", singer: "Shakira", src: "music/23.m4a" ,image: "image/23.jpeg"},
  { title: "La La La(Brazil 2014) ", singer: "Shakira", src: "music/24.m4a" ,image: "image/24.jpeg"},
  { title: "Waka Waka", singer: "Shakira", src: "music/25.m4a" ,image: "image/25.jpeg"},
  { title: "Senorita", singer: "Camila Cabello", src: "music/26.m4a" ,image: "image/26.jpeg"},
  { title: "Cheap Thrills", singer: "Sia", src: "music/27.m4a" ,image: "image/27.jpeg"},
  { title: "Dance Monkey", singer: "Tones And I", src: "music/28.m4a" ,image: "image/28.jpeg"},
  { title: "Bad Boy", singer: "Tungevaag, Raaban", src: "music/29.m4a" ,image: "image/29.jpeg"},
];